### ISSUE TITLE
Recive files, not drawing!

### ISSUE THREAD

**Issue by edulum** [pololu/minimu-9-ahrs-arduino#11]
![captura](https://cloud.githubusercontent.com/assets/15955448/11318339/8d313de8-904e-11e5-824d-c50e04c4efa8.PNG)

Hi! I've installed everything and arduino UNO is sending data througth serial port correctly. I can see how the numbers on Python Shell moves but isn't drawing (those windows doesn't respond). What can i do?

**Comment by kevin-pololu** [comment]
Since we resolved the problem on the Pololu forum (in [this topic](http://forum.pololu.com/viewtopic.php?f=32&t=10434)), I am closing this issue.
