### ISSUE TITLE
Slope

### ISSUE THREAD

**Issue by cagdaseckin** [pololu/minimu-9-ahrs-arduino#12]
Hi when i was trying your code on the desktop and steady  there is a slope. How can i fix this? Y axis is angle in degree X axis is time in seconds.
Pitch
![pitch](https://cloud.githubusercontent.com/assets/3118166/11633246/fd16f1e0-9d12-11e5-8f2d-e35fb40f9040.png)
Roll
![roll](https://cloud.githubusercontent.com/assets/3118166/11633244/fd1610b8-9d12-11e5-8832-9b7728831654.png)
Yaw
![yaw](https://cloud.githubusercontent.com/assets/3118166/11633245/fd166798-9d12-11e5-957e-39edb1dab563.png)

**Comment by kevin-pololu** [comment]
Hello,
If you are still having trouble with this, please contact us through our normal support channels to continue troubleshooting (https://www.pololu.com/contact). The GitHub issues are intended for tracking development of and bugs in the program itself.

If you contact us, it would be helpful for you to answer these questions:
- Which IMU and what microcontroller are you using? Please send a picture showing how you have them connected.
- Are you leaving the IMU board flat and stationary for a few seconds while the AHRS program starts up? This is necessary to calibrate the gyro and accelerometer zero-rate offsets.
- Did you calibrate the magnetometer and replace the calibration constants in the AHRS program with the values you got?
- Do the reported angles keep changing indefinitely at the same rate that your graphs show, or do they eventually level off?
