### ISSUE TITLE
NaN output

### ISSUE THREAD

**Issue by sudhar123** [pololu/minimu-9-ahrs-arduino#13]
I am trying to use the altIMU-10 V4 with this sketch and it starts off by giving me seemingly wrong values when it is stationary. When I took a look at the python GUI I saw that the yaw output was continuously spinning even when the IMU was stationary. When I moved the IMU, all the axis would start spinning and then give me a NaN output. I am using an Atmel 32U4 for testing. Could someone please point me in the right direction to figuring this out?

**Comment by kevin-pololu** [comment]
Hello,
If you are still having trouble with this, please contact us through our normal support channels to continue troubleshooting (https://www.pololu.com/contact). The GitHub issues are intended for tracking development of and bugs in the program itself.

If you contact us, it would be helpful for you to answer these questions:
- Have you checked the raw output of the sensors with the Serial examples to see whether they look reasonable?
- Are you leaving the IMU board flat and stationary for a few seconds while the AHRS program starts up? This is necessary to calibrate the gyro and accelerometer zero-rate offsets.
- Did you calibrate the magnetometer and replace the calibration constants in the AHRS program with the values you got?
