### ISSUE TITLE
Update for MinIMU-9 v5?

### ISSUE THREAD

**Issue by kd5ftn** [pololu/minimu-9-ahrs-arduino#15]
Pololu's latest revision of this board is the v5 which combines ST’s LSM6DS33 3-axis gyroscope and 3-axis accelerometer and LIS3MDL 3-axis magnetometer.

I'd like to use your code this new revision. I'd adapt it on my own, but I'm a non-engineer, and trying to set the proper registers is a bit out of my skill set.  If anyone else is able to add support for this board, I'll gladly help test it.

[LIS3MDL Datasheet: ](https://www.pololu.com/file/download/LIS3MDL.pdf?file_id=0J1089)

[LSM6DS33 Datasheet ](http://www2.st.com/content/ccc/resource/technical/document/datasheet/ed/aa/b8/e5/ab/3a/41/df/DM00157718.pdf/files/DM00157718.pdf/jcr:content/translations/en.DM00157718.pdf)

**Comment by kevin-pololu** [comment]
Hi, kd5ftn.

I just pushed an update for the program that adds support for the v5 IMUs.

Kevin

**Comment by kd5ftn** [comment]
Kevin,

Thanks for adding support for this sensor!
