### ISSUE TITLE
The output are always 0,0,0

### ISSUE THREAD

**Issue by asdico** [pololu/minimu-9-ahrs-arduino#16]
Hi, I'm trying to run this code, but my output are always PITCH: 0.00, ROLL: 0.00, YAW:0.00
I've tried to debus values and are like:

*******_MAGNETOM X: -746, MAGNETOM Y: -2198, MAGNETOM Z: 5760**_*****
!ROLL: 0.00, PITCH: -0.00, YAW: 0.00
EULER:
ANG:0.00,-0.01,0.00
ANALOGS:
AN:38,-68,-17,224,2,-120,-0.37,-1.10,2.88.

I'm using MinIMU-9 v5 
Could anyone help me?

**Comment by kevin-pololu** [comment]
If you are still having trouble with this, could you post on the [Pololu forum](https://forum.pololu.com/) or [contact us directly](https://www.pololu.com/contact)?

I'm going to close this issue for now as I don't suspect it to be a problem with the AHRS program code.
