### ISSUE TITLE
Yaw values

### ISSUE THREAD

**Issue by AhmadAbdi** [pololu/minimu-9-ahrs-arduino#18]
Hi there, sorry for the issue but i want to know that can i output the YAW values as integer instead of floating or character ?? means for e.g i want 90 instead of 90.36 etc
is it possible ? if possible then how can i get that?? sorry if i am asking a stupid question but i am very new to programming and want to learn with your help.

**Comment by kevin-pololu** [comment]
Github issues are not appropriate for asking a question like this; they are intended to keep track of problems with or improvements to the code in this repository. If you need help modifying the program to output integer angles, please post on the [Pololu forum](https://forum.pololu.com/) or consider asking for help from someone near you with more programming experience.
