### ISSUE TITLE
Calibration/Drift Issue

### ISSUE THREAD

**Issue by come** [pololu/minimu-9-ahrs-arduino#20]
hi,

I m a bit confused with the calibration, using the LIS3MDL calibrate code.

hardware:
- minimu 9 V5
- arduino uno

I upload the calibration sketch, and read the calibration values after 30seconds .
I get some values.
if i unplug replug my arduino, reupload the calibration sketch, i will get some totally different values

I did it severall time, let the minimu stand on a table, made the 8 movement etc.

never got some stable values for the calibration :'(

what is the issue ? is it normal ? 

many thanks for your help 

Note: i tried to upload minimu9ahrs.ino sketch with some values i got, but angles provided are drifting a lot

**Comment by kevin-pololu** [comment]
The best way to get calibration values is to point the IMU in as many different directions as possible; for example, imagine you are using the board to paint the inside of a sphere. Once you've done that, the numbers in the Calibrate sketch should no longer change much even if you continue to point the IMU in different directions.

If you continue to have trouble or have any other questions, please post on [the Pololu forum](https://forum.pololu.com/) or [contact us directly](https://www.pololu.com/contact). The GitHub issues are for keeping track of problems or improvements related to the code itself, which this doesn't appear to be, so I'm going to close this issue for now.

Kevin
