### ISSUE TITLE
python script not running

### ISSUE THREAD

**Issue by stephanschulz** [pololu/minimu-9-ahrs-arduino#24]
I am trying the python script on windows and macOS.
I followed the windows instruction and pretty sure all element are installed.
But both systems give me the same error.

Would you know what I am doing wrong?
Thank you.

On windows:
<img width="698" alt="Screen Shot 2020-01-15 at 3 22 29 PM" src="https://user-images.githubusercontent.com/1054816/72468383-06b9da00-37ab-11ea-81ab-93130464d22a.png">

On macOS:
`Stephan:minimu-9-ahrs-arduino-master stephanschulz$ python MinIMU-9-test.py
Traceback (most recent call last):
  File "MinIMU-9-test.py", line 39, in <module>
    from visual import *
ImportError: No module named visual
`

**Comment by kevin-pololu** [comment]
Could you make sure you installed VPython version 5.74 and not a newer version? The direct link to the Win32 Python 2.7 installer is here: http://vpython.org/contents/download/VPython-Win-Py2.7-5.74.exe
