### ISSUE TITLE
Gibberish

### ISSUE THREAD

**Issue by Kaleye** [pololu/minimu-9-ahrs-arduino#28]
Hello,
I just tried to run this code with an elegoo uno r3 and the altimu v 5 however when I open the serial port all I get is gibberish like this: 
Nɗ⸮⸮⸮N!⸮!qPq⸮⸮җ0⸮02⸮:⸮Oe::⸮*⸮.⸮:⸮

I uncommented the #define IMU_V5.
Is there anything else I should be doing?
Any ideas on why the output is gibberish?

**Comment by ketile** [comment]
Maybe the serial port is set to wrong speed?

**Comment by Kaleye** [comment]
I tested the Altimu and receive raw data from it just fine in the serial monitor ,so the speed should be fine.

**Comment by kevin-pololu** [comment]
If you are still having trouble with this, could you please post on the [Pololu forum](https://forum.pololu.com/) and clarify when you are able to get good output from the program and when you aren't?

We prefer to limit GitHub issues to bugs or requests related to the source code of the software itself, so I'm closing this issue for now.
