### ISSUE TITLE
Regarding changing of DPS full scale

### ISSUE THREAD

**Issue by copadragon88** [pololu/minimu-9-ahrs-arduino#9]
void Gyro_Init()
{
  gyro.init();
  gyro.enableDefault();
  gyro.writeReg(L3G::CTRL_REG4, 0x20); // 2000 dps full scale
  gyro.writeReg(L3G::CTRL_REG1, 0x0F); // normal power mode, all axes enabled, 100 Hz
}

Just wanted to check regarding the writing of registry. I wish to use a smaller dps full scale of 245. However I noticed a new registry written over CTRL_REG4 in Gyro_init which commented as 2000. Is it necessary for me to remove the current line with just the enable.default true? Thank you.

**Comment by kevin-pololu** [comment]
The last value written to the register will overwrite whatever was there previously, so you can either remove the 2000 dps line or add another call to `writeReg()` to set the full scale back to 245.

If you have further questions, please post on the [Pololu Forum](http://forum.pololu.com/) or [contact us directly](https://www.pololu.com/contact). (We prefer to use the GitHub issue tracker for development and bug reporting.)
